

using System.Collections.Generic;

class AllVehicleData : Information
{
    public void Vehicles()
    {
        vehicleDictionary.Add("kia sportage 2010", 16995);
        vehicleDictionary.Add("kia sportage 2011", 18295);
        vehicleDictionary.Add("kia sportage 2012", 18500);
        vehicleDictionary.Add("kia sportage 2013", 19000);
        vehicleDictionary.Add("kia sportage 2014", 21600);
        vehicleDictionary.Add("kia sportage 2015", 21900);
        vehicleDictionary.Add("kia sportage 2016", 22150);
        vehicleDictionary.Add("kia sportage 2017", 23200);
        vehicleDictionary.Add("kia sportage 2018", 23600);
        vehicleDictionary.Add("kia sportage 2019", 23750);
        vehicleDictionary.Add("kia sportage 2020", 23990);
        /*vehicleDictionary.Add("kia soul", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        vehicleDictionary.Add("", );
        */
    }

    public override void SaveToCSV() {}
}